### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by merks**
Include a link to the Oomph setup.

### CODE REVIEW

**Comment by merks** [comment]
@fipro78 

This adds the link to the contribution guide.

**Comment by merks** [comment]
Given this only changes a *.md file, the build failure seems not related.  And this build passed:

https://github.com/eclipse-nattable/nattable/pull/98

**Comment by fipro78** [comment]
@merks
Since the update of the target platform to a newer eclipse platform I see these test failures spawning sometimes. Looks like a concurrency issue that sometimes events are not fired when they should (at least in the test) and therefore the test fails. I have no idea why this happens since the update.

**Comment by merks** [comment]
I see. That’s very annoying and disconcerting. One can’t be sure if it’s a test case problem or a real framework problem.

**Comment by fipro78** [comment]
Yes, I am still searching for the cause. Hard to find because locally the tests succeed most of the time.

**Pull request merged**
